### ISSUE TITLE
Para a próxima reunião: 15-06

### ISSUE THREAD

**Issue by SenacProgWeb7Lagoas** [SenacProgWeb7Lagoas/projetointegrador#13]
* Finalizar as páginas com a responsividade implementada. ( SEM FALTA) 
@gleitons @MichelleAndrade @claudiaapj @SaVio-FrAncIsco @marcosfmd @marianibarbosa @PedroProgramador02 

* Footer Criada @lh-ude 

* Página de Resultado

* Página de Referência

* Pesquisa sobre as Ongs e sites de dicas de sustentabilidade #14

**Comment by BrytanniADJ** [comment]
![logo2](https://user-images.githubusercontent.com/99222703/163069945-0d2ad30c-2793-4dd9-a3ec-000aa81c26a4.png)
![logo3](https://user-images.githubusercontent.com/99222703/163069952-7c92d2e3-31ef-410e-ac67-5112cfb2acb5.png)
![logo1](https://user-images.githubusercontent.com/99222703/163069953-bb337b35-f909-40e3-bad7-126823a977dc.png)

Fiz 3 logos, mas posso melhorar eles depois ou criar mais, é rapidinho de fzr

**Comment by BrytanniADJ** [comment]
![156 sin título_20220412202729](https://user-images.githubusercontent.com/99222703/163070664-d473d1eb-c2d1-4abe-99fc-d2e3caf5ff6d.png)
![156 sin título_20220412202714](https://user-images.githubusercontent.com/99222703/163070667-d6595f97-7ee5-4095-b704-2fe0466465bc.png)

coloquei a logo de 2 jeitos, no fundo branco e encima da imagem

**Comment by lh-ude** [comment]
> * Finalizar as páginas com a responsividade implementada.
> * Logo Criada @BrytanniADJ
> * Footer Criada @lh-ude

**Comment by lh-ude** [comment]
@BrytanniADJ, tem como você disponibilizar a imagem png transparente da logo?

**Comment by wistech7l** [comment]
## fonte
Font Heveltica
cor da fonte no main preto 
font-size: 20 px

## cabecalho 1 ( o que tem o botão do modo escuro)
height: 100px;

## cabecalho com o menu
cabecalho do menu: com a cor do botao da pagina atual e o botao com borda branca
cabecalho do menu: com witdh de 70%, margin: 0 auto
height: 100px;

## botoes
font-size 20px
todos os botoes com radius border 5px

Texto do botão do modo escuro:  Modo escuro -> quando for claro 
                                Modo claro -> quando for escuro

## rodapé 
fotter heigth de 205px
Ideal seria copiar o da LUIZA

## main
main com texto a esquerda 
o titulo da pagina centralizado 
usar borda na cor do destaque ( semelhante a pagina de alimentacao )

**Comment by wistech7l** [comment]
* Bianca e Cláudia: Falta o JavaScript e faltava o footter ( quase finalizado). 

*  Mariani: Falta o JavaScript, o footter 

* Michelle, Gleiton e Pedro: JavaScript e footter.

* Luíza: Faltando o JavaScript, padronizar, estilizar a página de referências.

* Sávio: Padronizar o css, Padronizar Resultados.

**Comment by wistech7l** [comment]
Vamos adquear mais algumas coisas 
Usem como base o site que já está no Ar. 

O cabeçalho deve ser próximo ao que está disponível aqui: 
https://senacprogweb7lagoas.github.io/projetointegrador/residuos.html

E as perguntas deve ser próximos ao que está disponível aqui
https://senacprogweb7lagoas.github.io/projetointegrador/alimentacao.html

### Obs:
Lembrando que as o botão para mudar para próxima página deve está escrito 
*Próximo*
e a ultima página deve está escrito *Resultado*

Conferir o layout em telas com proporção 
_*1920 X 1080*_


Nossa próxima aula maior sobre o projeto será nossa penúltima antes da entrega/apresentação

Ainda nos falta a página de: 

- [ ] INDEX
- [ ] página de referência 
- [ ] Resultado com todas as respostas.

**Comment by lh-ude** [comment]
@wistech7l isley, para a próxima entrega eu fiquei com algumas dúvidas, principalmente com o javascript:

1- eu adaptei o meu js como o que estava no moradia, como faço pra debugar ou saber se está funcionado? 
2- o botão modo noturno está com aquele problema de só funcionar no segundo clique, mas quando ele é ativado, muda a paleta de cores e depois que desativa o modo noturno ele não volta ao normal (cor laranja).
![image](https://user-images.githubusercontent.com/99282366/173713581-465a8c4b-f6d4-44f3-b23f-c1b11b57579d.png)
![image](https://user-images.githubusercontent.com/99282366/173713603-c5703ccc-8f60-4b45-8471-23c753429dfd.png)
![image](https://user-images.githubusercontent.com/99282366/173713619-965ed534-c4a7-4945-b011-a00f6fb6da30.png)
3- Tem uma divisão entre os botões de navegação e a caixa abaixo, onde estão as perguntas, não sei como que remove. Não sei se é alguma medida de margem que ficou errada no CSS ou é um espaço que está sem classe.
4- A mesma coisa está acontecendo no footer, que está com uma barra cinza aparecendo por cima, no final da página.
![image](https://user-images.githubusercontent.com/99282366/173713677-c6ba5711-2e7d-4517-b120-b35801c9470c.png)

**Comment by wistech7l** [comment]
@lh-ude 
> 1- eu adaptei o meu js como o que estava no moradia, como faço pra debugar ou saber se está funcionado?


O moradia não tenho certeza se já estava completo todo o `js`, mas normalmente para debugar eu coloco `console.log` na função que desejo saber se a resposta está ok. 

> BUGs do Css

Sobre os bugs do modo noturno, precisava ver seu código, pode ser que o click esta associando com outras cores que era da página de alimentação.

Isso aqui não deveria estar dentro do `main` e sim no `header`
https://github.com/SenacProgWeb7Lagoas/projetointegrador/blob/consumo/consumo.html#L18-L38
```html
<body>
  <header>
    <button class="noturno" onclick="modoNoturno()">Modo noturno</button>
  </header>
  <main>
    <nav>
      <div class="cabecalho">
        <ul>
          <li>
            <a href="./moradia.html" class="button1">Moradia</a>
          </li>
          <li>
            <a href="./alimentacao.html" class="button2">Alimentação</a>
          </li>
          <li>
            <a href="./transporte.html" class="button3">Transporte</a>
          </li>
          <li>
            <a href="./consumo.html" class="button4">Consumo</a>
          </li>
          <li>
            <a href="./residuos.html" class="button5">Resíduos</a>
          </li>
        </ul>
      </div>
    </nav>
...
```

Sobre o rodapé vazar, tem que ver se adicionou as configurações adicionais que a Bianca criou e se isso não afetou o seu `css`.
