### ISSUE TITLE
Pagina Resultados

### ISSUE THREAD

**Issue by marcosfmd** [SenacProgWeb7Lagoas/projetointegrador#18]
Pagina Resultados com o fundo degrade com as cores de cada pagina
![degradre](https://user-images.githubusercontent.com/93166321/164128245-4753cae0-34f7-4523-bb79-0d227e9f3750.jpg)
.

**Comment by marcosfmd** [comment]
#Pagina Resultados

**Comment by marcosfmd** [comment]
Página Resultado com esse modelo diferente
![modelo-one](https://user-images.githubusercontent.com/93166321/164129372-624c0bf4-ab66-404f-b528-748e80abe1c5.jpg)
.

**Comment by marcosfmd** [comment]
Página Resultado com a imagem no fund
![img-fundo](https://user-images.githubusercontent.com/93166321/164333582-43f85c6e-63d3-46ce-a546-c32e6d2ac4b9.jpg)
o

**Comment by lh-ude** [comment]
> Pagina Resultado com o fundo branco ![fundo-branco](https://user-images.githubusercontent.com/93166321/164128393-170fee3b-a95b-4afb-a140-df4a63fd28d6.jpg) .

Um degradê em cada linha dessa, na cor correspondente às que já escolhemos para o cabeçalho ficaria como? 
Eu prefiro uma página mais limpa, mas tudo preto e branco fica sem graça e foge do estilo do resto do site.

**Comment by lh-ude** [comment]
> Página Resultado com a imagem no fund ![img-fundo](https://user-images.githubusercontent.com/93166321/164333582-43f85c6e-63d3-46ce-a546-c32e6d2ac4b9.jpg) o

ficou pesado e não sei se ficaria bem pra mobile

**Comment by wisley7l** [comment]
comentario teste
