### ISSUE TITLE
2- Alimentação

### ISSUE THREAD

**Issue by SenacProgWeb7Lagoas** [SenacProgWeb7Lagoas/projetointegrador#2]
@marianibarbosa
@claudiaapj
@BrytanniADJ

**Comment by wistech7l** [comment]
@claudiaapj e @BrytanniADJ  vamos precisar que vocês criem um pull request da branch de vocês para a branch `develop`

1- Cliquem na aba Pull Request aqui no GitHub
2- Create new Pull Request
3- Selecione a branch que vocês estão utilizando
4- alterem a base para `develop`, por padrão a base vem como `main`, mas precisamos mudar
5- No canto esquerdo em review podem me selecionar por favor. 
6- Criar o Pull Request
