### ISSUE TITLE
1- Moradia

### ISSUE THREAD

**Issue by SenacProgWeb7Lagoas** [SenacProgWeb7Lagoas/projetointegrador#3]
1 - Moradia - 3 perguntas

**Comment by wistech7l** [comment]
@marianibarbosa e @ericagalves vamos precisar que vocês criem um pull request da branch de vocês para a branch `develop`

1- Cliquem na aba Pull Request aqui no GitHub
2- Create new Pull Request
3- Selecione a branch que vocês estão utilizando
4- alterem a base para `develop`, por padrão a base vem como `main`, mas precisamos mudar
5- Clique em create pull request
6- No canto esquerdo em review podem me selecionar por favor. 
7- Clicar em o Create Pull Request novamente
