### ISSUE TITLE
4- Consumo

### ISSUE THREAD

**Issue by SenacProgWeb7Lagoas** [SenacProgWeb7Lagoas/projetointegrador#6]
4 - Consumo - 2 perguntas

**Comment by wistech7l** [comment]
@lh-ude vamos precisar que você crie um pull request da sua  branch para a branch `develop`

1- Clique na aba Pull Request aqui no GitHub
2- Create new Pull Request
3- Selecione a branch que você esta utilizando
4- Altere a base para `develop`, por padrão a base vem como `main`, mas precisamos mudar
5- Clique em create pull request
6- No canto esquerdo em review podem me selecionar por favor. 
7- Clicar em o Create Pull Request novamente

OBS.: Esse procedimento apenas uma única vez
