### ISSUE TITLE
E o FOOTER? 

### ISSUE THREAD

**Issue by SenacProgWeb7Lagoas** [SenacProgWeb7Lagoas/projetointegrador#7]
Precisamos decidir o que iremos colocar no Rodapé

**Comment by lh-ude** [comment]
Minha sugestão: 
Estava analisando a tabela que escolhemos para fazer a calculadora e na página 4 do arquivo tem uma tabela mostrando como interpretar o resultado. Esse [link](https://www.wwf.org.br/natureza_brasileira/especiais/pegada_ecologica/o_que_compoe_a_pegada/) explica que a nossa calculadora vai mostrar o resultado de quantos hectares são “utilizados” para gerar os recursos que consumimos.
O cálculo de quantas árvores precisam ser reflorestadas para compensar a emissão de carbono é feito quando o resultado é dado em toneladas de emissão de CO².

Acho que podemos fazer uma página de resultados, explicando como interpretar a pontuação, indicando alguns sites com dicas de iniciativas de sustentabilidade (como economizar água, energia, como reduzir emissão de resíduos) e indicaríamos algumas ONGs que trabalham reflorestamento e distribuição de mudas. De preferência ONGs regionais.

No rodapé, poderíamos colocar um disclaimer que esta é uma calculadora elaborada para fins acadêmicos e indicar outros sites com calculadoras mais completas, como as que já havíamos compartilhado e discutido na primeira reunião do projeto. 
Pensei em utilizarmos este estilo de rodapé, colocaríamos o logo do SENAC:

![image](https://user-images.githubusercontent.com/99282366/160188012-3bf3cfd6-3215-4479-9acb-7202977af06c.png)

**Comment by SenacProgWeb7Lagoas** [comment]
@lh-ude Depois coloca o print do Footer que você criou aqui so para termos referências.

**Comment by claudiaapj** [comment]
@lh-ude segue abaixo conforme solicitado na aula:
Git:   https://github.com/claudiaapj
Em relação ao nome favor colocar Cláudia Aguilar.

**Comment by wistech7l** [comment]
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/99540010/165189999-15d24942-334f-4fcb-81e6-8c745fa2a3bc.png)

**Comment by lh-ude** [comment]
Disponibilizo aqui o código do footer, junto com a documentação com algumas orientações.
Está faltando trabalhar a responsividade na minha página e elaborar o JS para computar as respostas (pretendo fazer isso amanhã).
Única alteração que vai ter de ser feita no código é o nome de vocês e alguns links.
Mas sugiro desde já que vocês testem o código já existente, já que cada um fez sua página de uma maneira e pode ter que revisar o seu próprio código.

https://github.com/SenacProgWeb7Lagoas/projetointegrador/tree/consumo/documentacao

![image](https://user-images.githubusercontent.com/99282366/165198663-ca8cb0ea-fb65-4a7b-80d3-7bb9c8c5cb2f.png)

**Comment by BrytanniADJ** [comment]
Nome: Bianca Araújo - Git: https://github.com/BrytanniADJ

**Comment by marianibarbosa** [comment]
conforme conversado na aula, deixo aqui meu perfil do linkedin:

https://br.linkedin.com/in/marianibarbosa

obrigada!!
